# Generated by Django 5.2 on 2025-05-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='thumbnail',
        ),
    ]
