# Generated by Django 5.2 on 2025-05-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticservice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='serviceareasection',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='link',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='storageservice',
            name='slug',
        ),
    ]
