# Generated by Django 5.2 on 2025-05-08 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intro_title', models.CharField(max_length=255)),
                ('intro_description', models.TextField()),
                ('overview_title', models.CharField(max_length=255)),
                ('overview_description', models.TextField()),
                ('benefits_title', models.CharField(max_length=255)),
                ('benefits', models.JSONField()),
                ('overview_image', models.ImageField(upload_to='infrastructure/automation/')),
            ],
        ),
        migrations.CreateModel(
            name='FirePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intro_title', models.CharField(max_length=255)),
                ('intro_text', models.TextField()),
                ('overview_title', models.CharField(max_length=255)),
                ('overview_text', models.TextField()),
                ('list_title', models.CharField(max_length=255)),
                ('overview_items', models.JSONField()),
                ('overview_image', models.ImageField(upload_to='infrastructure/fire/')),
            ],
        ),
        migrations.CreateModel(
            name='PowerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intro_title', models.CharField(max_length=255)),
                ('intro_text', models.TextField()),
                ('critical_systems', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StoragePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intro_title', models.CharField(max_length=255)),
                ('intro_prefix', models.CharField(max_length=255)),
                ('intro_suffix', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TruckLoadingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intro_title', models.CharField(max_length=255)),
                ('config_note', models.CharField(max_length=255)),
                ('average_rate', models.CharField(max_length=100)),
                ('truck_count', models.CharField(max_length=100)),
                ('intro_image', models.ImageField(upload_to='infrastructure/truck-loading/')),
            ],
        ),
        migrations.CreateModel(
            name='VesselCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VesselPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intro_title', models.CharField(max_length=255)),
                ('intro_text', models.TextField()),
                ('overview_title', models.CharField(max_length=255)),
                ('overview_text', models.TextField()),
                ('overview_list', models.JSONField()),
                ('overview_image', models.ImageField(upload_to='infrastructure/vessels/')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('features', models.JSONField()),
                ('image', models.ImageField(upload_to='infrastructure/automation/systems/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='infrastructure.automationpage')),
            ],
        ),
        migrations.CreateModel(
            name='AutoModeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_mode_steps', to='infrastructure.firepage')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='FireSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('features', models.JSONField()),
                ('image', models.ImageField(upload_to='infrastructure/fire/systems/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='infrastructure.firepage')),
            ],
        ),
        migrations.CreateModel(
            name='FireTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('items', models.JSONField()),
                ('image', models.ImageField(upload_to='infrastructure/fire/training/')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='infrastructure.firepage')),
            ],
        ),
        migrations.CreateModel(
            name='PowerMaintenanceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_steps', to='infrastructure.powerpage')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='PowerDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('features', models.JSONField()),
                ('image', models.ImageField(upload_to='infrastructure/power/distribution/')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='infrastructure.powerpage')),
            ],
        ),
        migrations.CreateModel(
            name='PowerSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('capacity', models.CharField(max_length=255)),
                ('response_time', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='infrastructure/power/systems/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='infrastructure.powerpage')),
            ],
        ),
        migrations.CreateModel(
            name='StorageSafetyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_blocks', to='infrastructure.storagepage')),
            ],
        ),
        migrations.CreateModel(
            name='StorageTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('features', models.JSONField()),
                ('image', models.ImageField(upload_to='infrastructure/storage/tanks/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='infrastructure.storagepage')),
            ],
        ),
        migrations.CreateModel(
            name='LoadingProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='infrastructure.truckloadingpage')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='LoadingBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('loading_rate', models.CharField(max_length=100)),
                ('features', models.JSONField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='infrastructure.truckloadingpage')),
            ],
        ),
        migrations.CreateModel(
            name='TruckLoadingSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('safety_list', models.JSONField()),
                ('efficiency_list', models.JSONField()),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety', to='infrastructure.truckloadingpage')),
            ],
        ),
        migrations.CreateModel(
            name='VesselCrewStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='infrastructure.vesselcrew')),
            ],
        ),
        migrations.CreateModel(
            name='VesselFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='infrastructure.vesselpage')),
            ],
        ),
        migrations.AddField(
            model_name='vesselcrew',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='infrastructure.vesselpage'),
        ),
        migrations.CreateModel(
            name='VesselSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('technical', 'Technical'), ('safety', 'Safety')], max_length=20)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='infrastructure.vesselpage')),
            ],
        ),
    ]
