# Generated by Django 5.2 on 2025-05-08 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationpage',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='automationsystem',
            name='features',
        ),
        migrations.RemoveField(
            model_name='firepage',
            name='overview_items',
        ),
        migrations.RemoveField(
            model_name='firesystem',
            name='features',
        ),
        migrations.RemoveField(
            model_name='firetraining',
            name='items',
        ),
        migrations.RemoveField(
            model_name='loadingbay',
            name='features',
        ),
        migrations.RemoveField(
            model_name='powerdistribution',
            name='features',
        ),
        migrations.RemoveField(
            model_name='storagetank',
            name='features',
        ),
        migrations.RemoveField(
            model_name='truckloadingsafety',
            name='efficiency_list',
        ),
        migrations.RemoveField(
            model_name='truckloadingsafety',
            name='safety_list',
        ),
        migrations.RemoveField(
            model_name='vesselpage',
            name='overview_list',
        ),
        migrations.AlterField(
            model_name='powerpage',
            name='critical_systems',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='AutomationBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='infrastructure.automationpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationSystemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='infrastructure.automationsystem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FireOverviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview_items', to='infrastructure.firepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FireSystemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='infrastructure.firesystem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FireTrainingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='infrastructure.firetraining')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PowerDistributionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='infrastructure.powerdistribution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageTankFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='infrastructure.storagetank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TruckLoadingEfficiencyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency_points', to='infrastructure.truckloadingsafety')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TruckLoadingSafetyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_points', to='infrastructure.truckloadingsafety')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VesselOverviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview_items', to='infrastructure.vesselpage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
