# Generated by Django 5.2 on 2025-04-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='button_one_link',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='button_one_text',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='button_two_link',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='button_two_text',
        ),
    ]
