# Generated by Django 5.2 on 2025-05-02 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_herosection_button_one_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientPartner',
        ),
        migrations.DeleteModel(
            name='InfrastructureFeature',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='whychooseusreason',
            name='description',
        ),
        migrations.RemoveField(
            model_name='whychooseusreason',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='infrastructuresection',
            name='feature_four_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infrastructuresection',
            name='feature_four_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infrastructuresection',
            name='feature_one_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infrastructuresection',
            name='feature_one_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infrastructuresection',
            name='feature_three_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infrastructuresection',
            name='feature_three_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infrastructuresection',
            name='feature_two_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infrastructuresection',
            name='feature_two_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseusreason',
            name='feature_four_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whychooseusreason',
            name='feature_four_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseusreason',
            name='feature_one_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whychooseusreason',
            name='feature_one_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseusreason',
            name='feature_three_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whychooseusreason',
            name='feature_three_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseusreason',
            name='feature_two_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whychooseusreason',
            name='feature_two_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='countries_served',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/featured/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='support_hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='years_experience',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructuresection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructuresection',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='infrastructure/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='home.clientpage'),
        ),
    ]
