# Generated by Django 5.2 on 2025-05-03 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompanyMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutCompanySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('overview', 'Overview'), ('history', 'History'), ('leadership', 'Leadership')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/company/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('our_identity', 'Our Identity'), ('our_principles', 'Our Principles'), ('our_strength', 'Our Strength')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('commitment', 'Environmental Commitment'), ('initiatives', 'Sustainability Initiatives')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='environment/')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FoundingStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='milestones/founding/')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ManagementTeamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MilestonePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SafetyPolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisionMissionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalBlockPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='about.environmentalblock')),
            ],
        ),
        migrations.AddField(
            model_name='environmentalblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='about.environmentalpage'),
        ),
        migrations.CreateModel(
            name='EnvironmentalPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='about.environmentalpage')),
            ],
        ),
        migrations.CreateModel(
            name='FoundingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='about.foundingstory')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('fleet', 'Fleet Modernization Program'), ('infrastructure', 'Infrastructure Development')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='investments/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='about.investmentpage')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_areas', to='about.investmentpage')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_info', to='about.investmentpage')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorInfoPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='about.investorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='about.milestonepage')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='about.milestonepage')),
            ],
        ),
        migrations.AddField(
            model_name='foundingstory',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founding_story', to='about.milestonepage'),
        ),
        migrations.CreateModel(
            name='SafetyPolicyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='safety/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='about.safetypolicypage')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='team/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='about.managementteampage')),
            ],
        ),
        migrations.CreateModel(
            name='VisionMissionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('vision', 'Vision'), ('mission', 'Mission')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vision-mission/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='about.visionmissionpage')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='about.visionmissionpage')),
            ],
        ),
        migrations.CreateModel(
            name='VisionMissionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='about.visionmissionblock')),
            ],
        ),
    ]
