# Generated by Django 5.2 on 2025-05-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutcompanysection_page_aboutsection_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorinfo',
            name='page',
        ),
        migrations.RemoveField(
            model_name='investorinfopoint',
            name='info',
        ),
        migrations.CreateModel(
            name='InvestmentBlockPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='about.investmentblock')),
            ],
        ),
        migrations.DeleteModel(
            name='InvestmentArea',
        ),
        migrations.DeleteModel(
            name='InvestorInfo',
        ),
        migrations.DeleteModel(
            name='InvestorInfoPoint',
        ),
    ]
