# Generated by Django 5.2 on 2025-05-03 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprintPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intro_title', models.CharField(max_length=255)),
                ('intro_description', models.TextField()),
                ('image', models.ImageField(upload_to='environment/carbon/')),
                ('volume_shipped', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intro_title', models.CharField(max_length=255)),
                ('intro_description', models.TextField()),
                ('image', models.ImageField(upload_to='environment/')),
            ],
        ),
        migrations.CreateModel(
            name='OilManagementPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intro_title', models.CharField(max_length=255)),
                ('intro_description', models.TextField()),
                ('image', models.ImageField(upload_to='environment/oil/')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='environment/initiatives/')),
                ('link', models.URLField()),
                ('stats', models.CharField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='environment.environmentalpage')),
            ],
        ),
        migrations.CreateModel(
            name='OilProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='environment.oilmanagementpage')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='OilSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('efficiency', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='environment/oil/systems/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='environment.oilmanagementpage')),
            ],
        ),
    ]
