# Generated by Django 5.2 on 2025-05-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalinitiative',
            name='link',
        ),
        migrations.RemoveField(
            model_name='environmentalinitiative',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='oilsystem',
            name='slug',
        ),
    ]
