# Generated by Django 5.2 on 2025-05-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_remove_environmentalinitiative_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilmanagementpage',
            name='volume_shipped',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilmanagementpage',
            name='image',
            field=models.ImageField(upload_to='environment/carbon/'),
        ),
    ]
