# Generated by Django 5.2 on 2025-05-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_oilmanagementpage_volume_shipped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilmanagementpage',
            name='intro_description',
        ),
        migrations.RemoveField(
            model_name='oilmanagementpage',
            name='intro_title',
        ),
        migrations.AlterField(
            model_name='oilmanagementpage',
            name='image',
            field=models.ImageField(upload_to='environment/oil/management/'),
        ),
    ]
