# Generated by Django 5.2 on 2025-05-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaarticle',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
